imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'g5HomeBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "g5HomeBundle", "g5AccountBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
# doctrine:
#     dbal:
#         driver:   %database_driver%
#         host:     %database_host%
#         port:     %database_port%
#         dbname:   %database_name%
#         user:     %database_user%
#         password: %database_password%
#         charset:  UTF8
#         # if using pdo_sqlite as your database driver, add the path in parameters.yml
#         # e.g. database_path: %kernel.root_dir%/data/data.db3
#         # path:     %database_path%

#     orm:
#         auto_generate_proxy_classes: %kernel.debug%
#         auto_mapping: true

# Mongodb Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%database_host%:%database_port%
            options: {}
    default_database: %database_name%
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOSUserBundle
fos_user:
    db_driver: mongodb # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: g5\AccountBundle\Document\User
    # group:
    #     group_class: g5\AccountBundle\Document\Group
    # encoder:
    #     algorithm: sha512
    #     encode_as_base64: false
    #     iterations: 10
    # registration:
    #     form:
    #         type: g5_registration_form_type
    #         handler: g5.registration.form.handler

# NelmioApiDocBundle
nelmio_api_doc: ~

# FOSRestBundle
fos_rest:
    param_fetcher_listener: force
    routing_loader:
        # default_format: json
        include_format: true
    view:
        formats:
            json: true

g5_tmdb:
    api_key: "%tmdb_api_key%"
    fixture_dir: "%kernel.root_dir%/../src/g5/TmdbBundle/Resources/fixtures/response"

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "@g5AccountBundle/Resources/config/serializer/fos"



fos_oauth_server:
    db_driver:  mongodb
    client_class:        g5\OAuthServerBundle\Document\Client
    access_token_class:  g5\OAuthServerBundle\Document\AccessToken
    refresh_token_class: g5\OAuthServerBundle\Document\RefreshToken
    auth_code_class:     g5\OAuthServerBundle\Document\AuthCode
    service:
        user_provider: fos_user.user_manager

nelmio_cors:
    defaults:
        allow_methods: ['POST', 'GET', 'PUT']
        allow_headers: ['*']
    paths:
        '^/oauth/v2/token':
            allow_origin: ['*']
        '^/api':
            allow_origin: ['*']
