<?php

namespace g5\MovieBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends DocumentRepository
{
    public function findByNameIn(array $labelNames)
    {
        return $qb = $this->createQueryBuilder()
            ->field('name')->in($labelNames)
            ->getQuery()
            ->execute();
    }
}
