<?php

namespace g5\MovieBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MoviemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviemRepository extends DocumentRepository
{
    public function findByTmdbId($id)
    {
        $q =  $this->createQueryBuilder()
                ->field('tmdb_id')->equals($id)
                ->getQuery();
        
        try {
            return $q->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findAll($skip = 0, $limit = 0, $sort = array('name' => 'name', 'order' => 'ASC'))
    {
        $q = $this->createQueryBuilder()
                ->skip($skip)
                ->limit($limit)
                ->sort($sort['name'], $sort['order'])
                ->getQuery();
        
        return $q->execute();
    }
    
    public function count() {
        $q = $this->createQueryBuilder()
                ->getQuery();
        
        return $q->execute()->count();
    }
}