<?php

/*
* This file is part of the mn-webapp package.
*
* (c) createproblem <https://github.com/createproblem/>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace g5\MovieBundle\Entity;

use Doctrine\ORM\EntityRepository;

use g5\AccountBundle\Entity\User;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends EntityRepository
{
    public function findLikeByName($name, User $user = null)
    {
        $parameters = array();

        $qb = $this->createQueryBuilder('l');
        $qb = $qb->where($qb->expr()->like('l.name', ':name'));
        $parameters[':name'] = $name.'%';

        if ($user !== null) {
            $qb = $qb->andwhere('l.user = :user');
            $parameters['user'] = $user;
        }

        $qb = $qb->setParameters($parameters);
        $qb = $qb->getQuery();

        return $qb->getResult();
    }
}
