<?php

/*
* This file is part of the mn-webapp package.
*
* (c) createproblem <https://github.com/createproblem/>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace g5\MovieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends EntityRepository
{
    /**
     * @param  string                        $name
     * @param  \g5\AccountBundle\Entity\User $user
     *
     * @return array
     */
    public function findByNameWithLike($name, \g5\AccountBundle\Entity\User $user)
    {
        $parameters = array();

        $qb = $this->createQueryBuilder('l');
        $qb = $qb->where($qb->expr()->like('l.name', ':name'))
            ->andwhere('l.user = :user')
            ->setParameters(array(
                ':name' => $name.'%',
                ':user' => $user,
            ))
            ->getQuery();

        return $qb->getResult();
    }
}
