<?php

namespace g5\MovieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function getMovieCountByUser(\g5\AccountBundle\Entity\User $user)
    {
        $query = $this->createQueryBuilder('m')
            ->select('count(m.id)')
            ->where('m.user=:user')
            ->setParameter(':user', $user)
            ->getQuery()
        ;

        $count = $query->getSingleScalarResult();

        return $count;
    }
}
