<?php
// src/g5/MovieBundle/Entity/MovieRepository
namespace g5\MovieBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function getCount()
    {
        $q = $this->createQueryBuilder('m')
                ->select('COUNT(m.id)')
                ->getQuery();
        
        try {
            $result = (int)$q->getSingleResult()[1];
        } catch (NoResultException $e) {
            $result = 0;
        }
        
        return $result;
    }
}
