<?php

namespace g5\AccountBundle\Repositroy;

use Doctrine\ODM\MongoDB\DocumentRepository;

use g5\AccountBundle\Document\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
    /**
     * Checks if the user unique.
     *
     * @param  User    $user The user object wich would be checked
     *
     * @return boolean       True if the user exists
     */
    public function isUnique(User $user)
    {
        return false;
    }
}
